CREATE TABLE ZH.BALOZOK ( id int not null primary key, 
                              nev varchar(40), 
                              evfolyam int);

INSERT INTO ZH.BALOZOK VALUES(1,'Baranyai János',2);
INSERT INTO ZH.BALOZOK VALUES(2,'Zala György',1);
INSERT INTO ZH.BALOZOK VALUES(3,'Békési Judit',1);
INSERT INTO ZH.BALOZOK VALUES(4,'Csongrádi Kata',2);
INSERT INTO ZH.BALOZOK VALUES(5,'Fejér Anna',3);
INSERT INTO ZH.BALOZOK VALUES(6,'Tolnai Balázs',2);
INSERT INTO ZH.BALOZOK VALUES(7,'Somogyi Péter',1);
INSERT INTO ZH.BALOZOK VALUES(8,'Vas János',2);
INSERT INTO ZH.BALOZOK VALUES(9,'Hajdú Eszter',1);
INSERT INTO ZH.BALOZOK VALUES(10,'Nógrádi Lajos',2);
INSERT INTO ZH.BALOZOK VALUES(11,'Heves Márton',2);
INSERT INTO ZH.BALOZOK VALUES(12,'Bács József',1);
INSERT INTO ZH.BALOZOK VALUES(13,'Pesti Barnabás',3);
INSERT INTO ZH.BALOZOK VALUES(14,'Buda Béla',1);
INSERT INTO ZH.BALOZOK VALUES(15,'Komáromi János',3);
INSERT INTO ZH.BALOZOK VALUES(16,'Gyõri Franciska',2);
INSERT INTO ZH.BALOZOK VALUES(17,'Soproni Barna',1);
INSERT INTO ZH.BALOZOK VALUES(18,'Veszprémi Pál',2);
INSERT INTO ZH.BALOZOK VALUES(19,'Zempléni Éva',2);
INSERT INTO ZH.BALOZOK VALUES(20,'Szabolcsi Bence',1);