/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package felulet;

import alaposztalyok.Balozok;
import alaposztalyok.Golya;
import alaposztalyok.Rendezes;
import alaposztalyok.ZeneSzam;
import globalis.Global;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.event.AncestorListener;

/**
 *
 * @author Rajkai
 */
public class GolyaBalPanel extends javax.swing.JPanel {

    private final String utvonal1 = "/adatok/balozok.txt";
    private final String utvonal2 = "/adatok/zenek.txt";
    private String CHAR_SET = "UTF-8";

    DefaultListModel<Balozok> balozokModell = new DefaultListModel<>();
    DefaultListModel<ZeneSzam> zeneszamModell = new DefaultListModel<>();
    DefaultListModel<ZeneSzam> valasztottZeneModell = new DefaultListModel<>();
    DefaultListModel<Balozok> tancModell = new DefaultListModel<>();

    Balozok balozo;
    Golya golya;

    /**
     * Creates new form GolyaBalPanel
     */
    public GolyaBalPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_balozok = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_zeneszam = new javax.swing.JList();
        btn_mutatas = new javax.swing.JButton();
        lbl_kivansag = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst_kivansag = new javax.swing.JList();
        lbl_tancolok = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_legtobbettancolok = new javax.swing.JList();

        setBackground(new java.awt.Color(255, 204, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Gólyabál");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel2.setText("Bálozók");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jLabel3.setText("Választható zeneszámok");

        lst_balozok.setToolTipText("");
        lst_balozok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lst_balozokMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(lst_balozok);

        jScrollPane2.setViewportView(lst_zeneszam);

        btn_mutatas.setText("Mulatás");
        btn_mutatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mutatasActionPerformed(evt);
            }
        });

        lbl_kivansag.setText(" ");

        jScrollPane3.setViewportView(lst_kivansag);

        lbl_tancolok.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        lbl_tancolok.setText("Legtöbbet táncolók");

        jScrollPane4.setViewportView(lst_legtobbettancolok);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(jLabel2)
                            .addGap(160, 160, 160)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(btn_mutatas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_kivansag, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tancolok)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_mutatas)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tancolok)
                    .addComponent(lbl_kivansag))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        beolvasBalozok();
        beolvasZenek();
        rendez();
        lbl_tancolok.setVisible(false);
    }//GEN-LAST:event_formAncestorAdded
    /*
    Hozzáadunk a Kívánság listához, egy Gólya által kiválasztott zenét!
     */
    private void lst_balozokMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_balozokMousePressed
        //A bálozók listájára kattintva, ha gólya a kiválasztott illető,
        //akkor „válasszon” egy véletlen zenét az adott kínálatból
        //(nyilván nem a másik listára való kattintással, hanem véletlen generálással,
        if (lst_balozok.getSelectedValue() != null) {
            Balozok balozok = (Balozok) lst_balozok.getSelectedValue();
            if (balozok.getEvFolyam().contains("1")) {
                lbl_kivansag.setText(balozok.getNev() + " kívánsága:");
                ZeneSzam zeneSzam;
                int veletlenZene;
                veletlenZene = (int) (Math.random() * zeneszamModell.size());
                zeneSzam = zeneszamModell.get(veletlenZene);

                ((Golya) balozok).kivalaszt(zeneSzam);

                valasztottZeneModell.clear();
                for (ZeneSzam szam : ((Golya) balozok).getZeneLista()) {
                    valasztottZeneModell.addElement(szam);
                }

                lst_kivansag.setModel(valasztottZeneModell);
                lst_kivansag.repaint();
            } else {
                lbl_kivansag.setText("");
                valasztottZeneModell.clear();

                lst_kivansag.setModel(valasztottZeneModell);
            }
        }

    }//GEN-LAST:event_lst_balozokMousePressed

    /*
    A mulatás gombra kattintva a bálozók kapnak random összeget.
    Random módon kapnak táncszámot is.
    A random metódus értékeit a Globál osztályból kapják meg.
    */
    
    private void btn_mutatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mutatasActionPerformed
        lbl_tancolok.setVisible(true);
        int fogyasztas = (int) (Math.random() * (Global.FELSO_FOGYASZTAS - Global.ALSO_FOGYASZTAS + 1) + Global.ALSO_FOGYASZTAS);

        int tancoloIndex = (int) (Math.random() * balozokModell.size()); 
        Balozok tancolo = balozokModell.get(tancoloIndex);
        tancolo.tancol();

        int penzkoltoIndex = (int) (Math.random() * balozokModell.size()); 
        Balozok penzkolto = balozokModell.get(penzkoltoIndex); 
        penzkolto.fogyaszt(fogyasztas);

        tancModell.clear();

        int max = balozokModell.get(0).getTancainakSzama();

        for (int i = 0; i < balozokModell.size(); i++) {
            if (balozokModell.get(i).getTancainakSzama() > max) {
                max = balozokModell.get(i).getTancainakSzama();
            }
        }

        for (int i = 0; i < balozokModell.size(); i++) {
            if (balozokModell.get(i).getTancainakSzama() == max) {
                tancModell.addElement(balozokModell.get(i));
            }
        }

        lst_legtobbettancolok.setModel(tancModell);
        lst_legtobbettancolok.repaint();
        lst_balozok.repaint();
    }//GEN-LAST:event_btn_mutatasActionPerformed

    private void beolvasBalozok() {
        InputStream ins = this.getClass().getResourceAsStream(utvonal1);
        Scanner scan = new Scanner(ins, CHAR_SET);
        String sor;
        String[] adatok;

        while (scan.hasNextLine()) {
            sor = scan.nextLine();
            adatok = sor.split(";");
            if (adatok[1].equals("1")) {
                balozo = new Golya(adatok[0], adatok[1]);
            } else {
                balozo = new Balozok(adatok[0], adatok[1]);
            }

            balozo.zsebPenz(((int) (Math.random() * (Global.FELSO_ERTEK - Global.ALSO_ERTEK + 1) + Global.ALSO_ERTEK)));
            balozokModell.addElement(balozo);
        }

        lst_balozok.setModel(balozokModell);

    }

    private void beolvasZenek() {
        InputStream ins = this.getClass().getResourceAsStream(utvonal2);
        Scanner scan = new Scanner(ins, CHAR_SET);
        String sor;
        String[] adatok;
        ZeneSzam zeneSzam;
        while (scan.hasNextLine()) {
            sor = scan.nextLine();
            adatok = sor.split(";");
            zeneSzam = new ZeneSzam(adatok[0], adatok[1]);
            zeneszamModell.addElement(zeneSzam);

        }
        lst_zeneszam.setModel(zeneszamModell);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mutatas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_kivansag;
    private javax.swing.JLabel lbl_tancolok;
    private javax.swing.JList lst_balozok;
    private javax.swing.JList lst_kivansag;
    private javax.swing.JList lst_legtobbettancolok;
    private javax.swing.JList lst_zeneszam;
    // End of variables declaration//GEN-END:variables

    private void rendez() {
        List<Balozok> balozokList = Collections.list(balozokModell.elements());
        Collections.sort(balozokList);
        Collections.sort(balozokList, new Rendezes());
        balozokModell.clear();
        for (Balozok balozok : balozokList) {
            balozokModell.addElement(balozok);
        }
    }
}
